created by: <a href=https://github.com/morkapronczay>morkapronczay</a>

In [1]:
import numpy as np

In [2]:
array = np.array([[1,2], [3,4]])
array

array([[1, 2],
       [3, 4]])

In [3]:
array.shape

(2, 2)

In [4]:
flat_array = array.flatten()
flat_array

array([1, 2, 3, 4])

In [5]:
flat_array.shape

(4,)

In [6]:
ravel_array = np.ravel(array)
ravel_array

array([1, 2, 3, 4])

In [7]:
ravel_array.shape

(4,)